yugal07/FitTrack-

client/.gitignore
client/src/App.jsx
client/src/components/auth/ProtectedRoute.jsx
client/src/components/layout/Header.jsx
client/src/components/layout/MainLayout.jsx
client/src/context/AuthContext.jsx
client/src/pages/Login.jsx
client/src/pages/Profile.jsx
client/src/pages/Register.jsx
client/src/services/api.js
client/src/services/authService.js
client/src/services/userService.js
server/controllers/authController.js
server/index.js
server/middleware/authMiddleware.js
server/models/userModel.js
server/seeder/data/users,js
server/seeder/index.js

fixed the login/register functionality and added user data in seedData

---

client/.dockerignore
client/Dockerfile.client
docker-compose.yml
server/Dockerfile.server

Dockerized

---

client/src/styles/global.css

fixed issue-Square while registering email and password

---

client/src/App.jsx
client/src/components/layout/MainLayout.jsx
client/src/components/layout/Sidebar.jsx
client/src/pages/workout/WorkoutDetailPage.jsx
client/src/pages/workout/WorkoutFormPage.jsx
client/src/pages/workout/WorkoutHistoryPage.jsx
client/src/pages/workout/WorkoutPage.jsx
client/src/pages/workout/WorkoutSessionPage.jsx
client/src/services/api.js
client/vite.config.js
server/middleware/authMiddleware.js

workout pages

---

client/src/components/layout/Header.jsx

fixed issue 26

---

server/documentation/goals/goalController.md

HI NIVEDITA PLEASE REVIEW @Nivedita-Chhokar @DEEPANSHI-02

Documentation for goal

---

client/src/App.jsx
client/src/components/layout/Layout.jsx
client/src/components/workout/AvailableWorkout.jsx
client/src/components/workout/ExerciseForm.jsx
client/src/components/workout/WorkoutDetail.jsx
client/src/components/workout/WorkoutForm.jsx
client/src/components/workout/WorkoutList.jsx
client/src/components/workout/Workouts.jsx

Implementing Workout Pages

---

client/src/App.jsx
client/src/components/admin/AdminDashboard.jsx
client/src/components/admin/AdminLayout.jsx
client/src/components/admin/analytics/AnalyticsDashboard.jsx
client/src/components/admin/content/ExerciseForm.jsx
client/src/components/admin/content/ExerciseManager.jsx
client/src/components/admin/content/NutritionItemForm.jsx
client/src/components/admin/content/NutritionManager.jsx
client/src/components/admin/content/WorkoutForm.jsx
client/src/components/admin/content/WorkoutManager.jsx
client/src/components/admin/notifications/AnnouncementCreator.jsx
client/src/components/admin/notifications/NotificationHistory.jsx
client/src/components/admin/users/UserDetail.jsx
client/src/components/admin/users/UserList.jsx
client/src/components/auth/AuthGuard.jsx
client/src/components/auth/Login.jsx
client/src/contexts/AuthContext.jsx
client/src/routes/AdminRoutes.jsx
client/src/services/adminService.js
server/controllers/adminController.js
server/controllers/authController.js
server/controllers/nutritionDatabaseController.js
server/index.js
server/models/NutritionItem.js
server/routes/adminNutritionRoutes.js
server/routes/adminRoutes.js
server/routes/exerciseRoutes.js

To Check -- 
git remote add upstream https://github.com/yugal07/FitTrack-.git
git fetch upstream
git checkout -b develop-admin upstream/develop-admin
npm install on both server and client
npm run dev
Credentials - admin@example.com  pass - admin123
Comment if you find bugs or broken features

Admin Dashboard Complete

---

server/documentation/goals/Models/model.md

@Nivedita-Chhokar @DEEPANSHI-02 Review this

Documentation for models 

---

client/package-lock.json
client/package.json
client/src/App.jsx
client/src/components/admin/content/NutritionItemForm.jsx
client/src/components/admin/notifications/AnnouncementCreator.jsx
client/src/components/auth/ChangePassword.jsx
client/src/components/auth/ForgotPassword.jsx
client/src/components/auth/Login.jsx
client/src/components/auth/Register.jsx
client/src/components/auth/ResetPassword.jsx
client/src/components/goals/GoalWizard.jsx
client/src/components/nutrition/DailyIntakeForm.jsx
client/src/components/profile/MeasurementForm.jsx
client/src/components/profile/PhotoForm.jsx
client/src/components/profile/ProfileEditForm.jsx
client/src/components/workout/ExerciseForm.jsx
client/src/components/workout/WorkoutForm.jsx

Fixes: #11 
@yugal07 PTAL, let me know if any other files require changes

implementing form validation and used react-hook-form

---

client/src/components/auth/Register.jsx
client/src/components/nutrition/DailyIntakeForm.jsx

Fixes: #64 
@sancheet230  PTAL

Fixing Register Form

---

client/src/components/progress/ProgressReport.jsx

Fixes: #37 
@yugal07 @DEEPANSHI-02  PTAL
Downloading PDF:
PDF content:

Fixed generatePDF in progress report

---

client/package-lock.json
client/package.json
client/src/components/auth/Register.jsx

Enhanced User onboarding flow

---

client/src/App.jsx
client/src/components/layout/Layout.jsx
client/src/components/notifications/NotificationBell.jsx
client/src/components/notifications/Notifications.jsx
client/src/services/notificationService.js

Notification Acceptance for user

---

README.md
client/src/components/auth/ResetPassword.jsx
server/.env.example
server/controllers/authController.js
server/models/userModel.js
server/package-lock.json
server/package.json
server/routes/authRoutes.js
server/services/emailService.js

Feat: Added Forgot Password Functionality

---

client/src/components/nutrition/Nutrition.jsx
client/src/components/nutrition/WaterTracker.jsx
server/controllers/nutritionController.js

@DEEPANSHI-02
The issue was that when a user updated their water intake, the app would immediately show the new amount (to make it feel fast), but it wasn’t correctly syncing with the backend — especially when there was no nutrition log yet for that day. Even though the backend saved the data, the app didn’t update its local state with the actual response from the server. So the water intake would look correct at first, but go back to zero when you left and came back to the page.
The fix was to update the function that handles water changes so it works properly whether it's updating an existing log or creating a new one. It now uses the real data returned from the backend to update the app’s local state. Also added proper use of async/await in the WaterTracker component to make sure …

Fixed the persistance of the water tracker

---

client/src/components/nutrition/MealPlanner.jsx
client/src/components/profile/MeasurementsTracker.jsx
client/src/components/profile/ProgressPhotos.jsx
client/src/components/workout/WorkoutList.jsx

fixes#95 @yugal07 @Nivedita-Chhokar  PTAL

Migration from window.confirm to confirmModal

---

client/package-lock.json
client/package.json
client/src/components/nutrition/MealPlanner.jsx
client/src/components/nutrition/Nutrition.jsx
client/src/components/nutrition/NutritionStats.jsx
client/src/components/nutrition/WaterChart.jsx

1. Implemented Recharts for nutrition stats.
2. Fixed MealPlanner null issue.
3. Implemented Water Intake chart on dailyOverview.

Updated Nutrition page

---

server/middleware/errorMiddleware.js
server/models/userModel.js
server/routes/notificationRoutes.js
server/services/notificationScheduler.js

Fixes Issues: 
- #78 
- #77 
- #76 
- #75

Linting issues

---

server/controllers/adminController.js
server/controllers/authController.js
server/controllers/nutritionController.js

fixes :
Lint nutritionController #73 
Lint authController #71 
Lint adminController #70 
@yugal07 PTAL

fixed linting 

---

client/src/components/nutrition/NutritionGoals.jsx
server/controllers/nutritionGoalsController.js
server/models/NutritionGoals.js
server/models/nutritionLogModel.js
server/routes/nutritionRoutes.js

 Fetched Nutrition Goals from db 
